### ISSUE TITLE
Práctica: Aprender Generador de Contenidos Estáticos (Jekyll) -- TERMINADA

### ISSUE THREAD

**Issue by davidairam** [ULL-MFP-AET-2021/p04-t0-aprender-jekyll-davidairam#2]
Ver README.md de la rama main, ahí encontrará los links.

En la rama "master" está todo el repl.it de desarrollo de la práctica, en la "main" solo la carpeta "site", es decir el sitio web que está colgado en githubpages de este repo.

Añado el readme.md a las prácticas anteriores.

@crguezl gracias por el tiempo extra. Le he dedicado algo de tiempo y la práctica ha sido bastante completa y he aprendido bastante. No conocía nada de jekyll, liquid, repl.it etc. Lo mío hasta ahora era mucho C, Java, Android, Kotlin y C# 👍 

Hice uso de todo lo que pedía en la práctica: 

- datos comunes en un json en carpeta _data
- layouts propios
- uso de colecciones
- colecciones futuribles
- markdown mezclado con html
- modificaciones en el css
- Soporte para LateX.
- código propio
- uso continuo de git.
- imagenes locales y externas
- jugar mucho con liquid
etc.

He aprendido mucho, gracias Casiano.

**Comment by crguezl** [comment]
¡Estupendo trabajo @davidairam ! 👍 🚀 ⭐ 
Me ha gustado.

**Comment by crguezl** [comment]
Te he puesto el enlace a la página en el about del repo

**Comment by davidairam** [comment]
Gracias @crguezl !!
Sigo con el resto de prácticas aunque no tengo mucho tiempo :/
